package org.andjos.susfund.entity.caseentity;

public enum CaseStatus {
    UNHANDLED,
//    UNDER_SUPPORT_PREPARATION,
//    UNDER_PAYMENT_PREPARATION,
//    UNDER_SUPPORT_DECISION,
//    UNDER_PAYMENT_DECISION,

    //TODO FIX CURRENT STATE MAP IN STATEMACHINE TO MATCH THIS SETUP
    //TODO FIX INIT.SQL SCRIPT TO MATCH THIS SETUP -- OR USE FLYWAY TO CHANGE CASES
    UNDER_PREPARATION,
    UNDER_DECISION,
    UNDER_DISPATCH,
    REJECTED,
    CLOSED,
    IN_WAITING
}
