FROM quay.io/wildfly/wildfly

COPY ./wildfly-config/com /opt/jboss/wildfly/modules/com

COPY ./wildfly-config/config-script.cli /opt/jboss/config-script.cli

COPY ./wildfly-config/logging-script.cli /opt/jboss/logging-script.cli

RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/logging-script.cli

RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/config-script.cli

RUN rm -Rf /opt/jboss/wildfly/standalone/configuration/standalone_xml_history/*

RUN /opt/jboss/wildfly/bin/add-user.sh admin test1234

WORKDIR /opt/jboss/wildfly/standalone/deployments

COPY ./susfund-rest/target/*.war ./susfund.war

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]