services:
  susfund-fe:
    container_name: susfund-fe
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80"
    environment:
      - BE_HOST=localhost
      - BE_PORT=8080
    networks:
      - susfund

  db:
    container_name: susfund-db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "7777:3306"
    networks:
      - susfund
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest1234" ]
      interval: 5s
      timeout: 5s
      retries: 100

  wildfly:
    container_name: susfund-wildfly
    build:
      context: .
      dockerfile: Dockerfile.wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - susfund
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=susfund_db
      - DB_USERNAME=root
      - DB_PASSWORD=test1234
    depends_on:
      db:
        condition: service_healthy

networks:
  susfund: