FROM quay.io/wildfly/wildfly

COPY ./wildfly-config/com /opt/jboss/wildfly/modules/com

COPY ./wildfly-config/config-script.cli /opt/jboss/config-script.cli

COPY ./wildfly-config/logging-script.cli /opt/jboss/logging-script.cli

COPY ./target/SusFund-1.0-SNAPSHOT.war ./SusFund-1.0-SNAPSHOT.war

RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/logging-script.cli

RUN /opt/jboss/wildfly/bin/jboss-cli.sh --file=/opt/jboss/config-script.cli

RUN rm -Rf /opt/jboss/wildfly/standalone/configuration/standalone_xml_history/*

COPY ./wildfly-config/start.sh /opt/jboss/start.sh

CMD ["/opt/jboss/start.sh"]