services:
  susfund-fe:
    container_name: susfund-fe
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    networks:
      - susfund

  db:
    container_name: susfund-db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
     - "7777:3306"
    networks:
      - susfund
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest1234" ]
      interval: 5s
      timeout: 5s
      retries: 100

  wildfly:
    container_name: susfund-wildfly
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - susfund
    depends_on:
       db:
        condition: service_healthy

networks:
  susfund: