services:
  susfund-fe:
    container_name: susfund-fe
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    networks:
      - susfund

  db:
    container_name: susfund-db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
     - "7777:3306"
    networks:
      - susfund

  wildfly:
    container_name: susfund-wildfly
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - susfund
    depends_on:
      - db

networks:
  susfund: