<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.andreasoo</groupId>
    <artifactId>SusFund</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>


  <artifactId>susfund-repository</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>susfund-repository</name>
  <packaging>jar</packaging>


  <properties>
    <flyway.version>10.17.0</flyway.version>
  </properties>

  <dependencies>

    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-core</artifactId>
      <version>${flyway.version}</version>
    </dependency>

    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-mysql</artifactId>
      <version>${flyway.version}</version>
    </dependency>

    <dependency>
      <groupId>jakarta.ejb</groupId>
      <artifactId>jakarta.ejb-api</artifactId>
      <version>4.0.1</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.andreasoo</groupId>
      <artifactId>susfund-common</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>

  </dependencies>

  <build>

    <plugins>

      <plugin>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-maven-plugin</artifactId>
        <version>${flyway.version}</version>
        <configuration>
          <url>jdbc:mysql://localhost:7777/susfund_db?useSSL=false&amp;serverTimezone=UTC</url>
          <user>root</user>
          <password>test1234</password>
          <locations>
            <location>classpath:db/migration</location>
          </locations>
          <baselineOnMigrate>true</baselineOnMigrate>
          <validateOnMigrate>true</validateOnMigrate>
          <outOfOrder>false</outOfOrder>
          <validateMigrationNaming>true</validateMigrationNaming>
          <mixed>true</mixed>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.32</version>
          </dependency>
        </dependencies>
      </plugin>

    </plugins>

  </build>

</project>